services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --socket=/tmp/mysql.sock
      - --character-set-server=utf8
      # - --collation-server=utf8_general_ci
      # - --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  web:
    build: .
    volumes:
      - ./www:/var/www/html
    ports:
      - 8000:80
