services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  web:
    build:
      context: .
      args:
        PHP_VERSION: 8.0
    volumes:
      - ./www:/var/www/html
    ports:
      - 8000:80
