services:
  web:
    build:
      args: { PHP: 8.2 }
    volumes:
      - ./www:/var/www/html
      - ./system/:/root/
    ports:
      - 8000:80

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
