services:
  db:
    # image: mysql:8.0
    image: mariadb:11.4
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  web:
    build: .
    volumes:
      - ./www:/var/www/
      - ./system/:/root/
    ports:
      - 8000:80
      - 8443:443
