services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --socket=/tmp/mysql.sock
      - --character-set-server=utf8
      # - --collation-server=utf8_general_ci
      # - --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  web:
    image: php:apache
    environment:
      ext: mysqli pdo_mysql
    volumes:
      - ./www:/var/www/html
    ports:
      - 8000:80
    command: >
      bash -c "docker-php-ext-install $$ext &&
      a2enmod rewrite &&
      apache2-foreground"
